apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: synapsemedic-com-tls
spec:
  secretName: synapsemedic-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: synapsemedic.com
  dnsNames:
    - synapsemedic.com
    - www.synapsemedic.com
